[package]
name = "hwaas"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.6.20"
clap = { version = "4.4.0", default-features = false, features = ["derive", "error-context", "help", "std", "usage"] }
tokio = { version = "1.34.0", features = ["full"] }
